backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    widget: "object"
    preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "text", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: Image, name: image, widget: image }
      - { label: Slide, name: slide, widget: image }
      - label: "Client Type"
        name: "client"
        widget: "relation"
        collection: "client"
        searchFields: ["title", "text"]
        valueField: "title"
        displayFields: ["Title"]
      - label: "Discipline Type"
        name: "discipline"
        widget: "relation"
        collection: "discipline"
        searchFields: ["title", "text"]
        valueField: "title"
        displayFields: ["Title"]
  - name: "discipline"
    label: "Discipline"
    folder: "content/discipline"
    create: true
    slug: "{{slug}}"
    widget: "object"
    preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
  - name: "client"
    label: "Type of Client"
    folder: "content/client"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    widget: "object"
    preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
