backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    widget: "object"
    preview: true
    fields:
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: "works",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "text", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: image, widget: image }
      - { label: "Slide", name: slide, widget: image }
      - label: "Client Type"
        name: "clients"
        widget: "relation"
        collection: "clients"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "Discipline Type"
        name: "disciplines"
        widget: "relation"
        multiple: true
        collection: "disciplines"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
  - name: "disciplines"
    label: "Disciplines"
    folder: "content/disciplines"
    create: true
    slug: "{{slug}}"
    widget: "object"
    preview: true
    fields:
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: "disciplines",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
  - name: "clients"
    label: "Type of Client"
    folder: "content/clients"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    widget: "object"
    preview: true
    fields:
      - {
          label: "Collection",
          name: "collection",
          widget: "hidden",
          default: "clients",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "text", widget: "string" }
